### ISSUE TITLE
UI not declared 

### ISSUE THREAD

**Issue by rakusan2** [FRCDashboard/FRCDashboard-Tuning#1]
Your first line should check if `ui` exists and if not then create it otherwise error will happen

**Comment by rakusan2** [comment]
You can also inform people to make sure that the script runs after ui.js

**Comment by ErikBoesen** [comment]
Would there be any situation in which `ui` wouldn't exist?

**Comment by rakusan2** [comment]
In the [NetworkTables issue](https://github.com/FRCDashboard/FRCDashboard/issues/37) he originaly had the script tag in the head which resulted in ui not existing

**Comment by ErikBoesen** [comment]
Unless the user doesn't follow the README's installation directions, they won't have that problem. I don't think it's reasonable to add a check for that to every addon.
